# Generated by Django 5.0.6 on 2024-06-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neris_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('nerid_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeptHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neris_id_dept', models.CharField(max_length=20)),
                ('internal_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
