# Generated by Django 5.0.6 on 2024-06-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neris_app', '0002_dept_depthist'),
    ]

    operations = [
    ]
