# Generated by Django 5.0.6 on 2024-06-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neris_app', '0004_companyadmin_developer_moderator_delete_dept_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAdmin',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
