# Generated by Django 5.0.6 on 2024-06-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_item_alter_member_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='current_organization',
            new_name='organization',
        ),
    ]
